[project]
name = "symbiotic-transformers"
version = "0.1.0"
description = ""
readme = "README.md"
dependencies = [
    "jax",
    "jaxlib",
    "flax",
    "tensorflow",
    "requests",
    "ipykernel",
    "tqdm",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
